name: CI

on:
  push:
    branches: [main]
    tags:
      - '[0-1].[0-9]+.[0-9]+-[0-9]'
  pull_request:
    branches: [main]

jobs:
  lint:
    name: luacheck
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Cache Key
        id: luver-cache-key
        env:
          CI_RUNNER_OS: ${{ runner.os }}
          CI_SECRETS_CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: |
          echo "::set-output name=value::${CI_RUNNER_OS}-luver-${CI_SECRETS_CACHE_VERSION}-luacheck-$(date -u +%Y-%m-%d)"
        shell: bash
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/luver
          key: ${{ steps.luver-cache-key.outputs.value }}
      - name: Setup Lua
        uses: MunifTanjim/luver-action@v1
        with:
          default: 5.1.5
          lua_versions: 5.1.5
          luarocks_versions: 5.1.5:3.8.0
      - name: Setup luacheck
        run: |
          luarocks install luacheck
      - name: Lint
        run: ./scripts/lint.sh --no-cache

  format:
    name: stylua
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check Format
        uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          version: 0.13.1
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check llhttp/

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Cache Key
        id: luver-cache-key
        env:
          CI_RUNNER_OS: ${{ runner.os }}
          CI_SECRETS_CACHE_VERSION: ${{ secrets.CACHE_VERSION }}
        run: |
          echo "::set-output name=value::${CI_RUNNER_OS}-luver-${CI_SECRETS_CACHE_VERSION}-build-$(date -u +%Y-%m-%d)"
        shell: bash
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/luver
          key: ${{ steps.luver-cache-key.outputs.value }}
      - name: Setup Lua
        uses: MunifTanjim/luver-action@v1
        with:
          default: 5.1.5
          lua_versions: 5.1.5
          luarocks_versions: 5.1.5:3.8.0
      - name: Build
        run: |
          ./scripts/make-rockspec.sh dev-1
          luarocks make --no-install llhttp-dev-1.rockspec
